apiVersion: v1 
kind: Pod 
metadata: 
  name: liveness-http 
spec: 
  containers: 
  - name: liveness
    image: smlinux/unhealthy 
    ports: 
        - containerPort: 80
          protocol: TCP 
    livenessProbe: 
      httpGet:
        path: /
        port: 8080
      initialDelaySeconds: 2 #Default 0 
      periodSeconds: 2 #Default 10 
      timeoutSeconds: 1 #Default 1 
      successThreshold: 1 #Default 1 
      failureThreshold: 3 #Default 3

