apiVersion: v1 #사용하는 쿠버네티스 API 버전
kind: Pod # 어떤 종류의 Object를 생성하는지 
metadata: #이름, 네임스페이스, 라벨를 포함하여 Object를 유일하게 Object를 구분지어 주는 데이터
  name: nginx
  labels:
    env: test
spec:
  containers:
  - name: nginx
image: nginx
